Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0"
    Option         "AllowEmptyInitialConfiguration" "True"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    Option         "AllowEmptyInitialConfiguration" "True"
    Option         "UseDisplayDevice" "None"
    Option         "ConnectedMonitor" "DFP-0"
    Option         "MetaModes" "1920x1080+0+0"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    DefaultDepth    24
    Option         "AllowEmptyInitialConfiguration" "True"
    Option         "UseDisplayDevice" "None"
    SubSection     "Display"
        Depth       24
        Virtual     1920 1080
    EndSubSection
EndSection
