Section "ServerFlags"
    Identifier     "ServerFlags0"
    Option         "AutoAddGPU" "false"
    Option         "AllowMouseOpenFail" "true"
    Option         "DontVTSwitch" "true"
EndSection

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    Option         "AllowEmptyInitialConfiguration" "True"
    Option         "ConnectedMonitor" "DFP-0"
    Option         "CustomEDID" "DFP-0:/etc/X11/edid-1080p.bin"
    Option         "IgnoreEDIDChecksum" "DFP-0"
    Option         "ModeValidation" "NoMaxPClkCheck, NoEdidMaxPClkCheck, AllowNonEdidModes, NoVirtualSizeCheck"
    Option         "MetaModes" "DFP-0: 1920x1080 +0+0"
    Option         "DPI" "96 x 96"
    Option         "Coolbits" "0"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    DefaultDepth    24
    Option         "AllowEmptyInitialConfiguration" "True"
    SubSection     "Display"
        Depth       24
        Modes       "1920x1080"
        Virtual     1920 1080
    EndSubSection
EndSection

Section "Extensions"
    Option         "MIT-SHM" "Enable"
    Option         "RANDR" "Enable"
EndSection
